cat <<EOF > backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-backend
  namespace: smartops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartops-backend
  template:
    metadata:
      labels:
        app: smartops-backend
    spec:
      containers:
        - name: backend
          image: sunilak05/smartops-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
EOF

